# Generated by Django 5.0.7 on 2024-12-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="Income",
        ),
        migrations.AddField(
            model_name="basetransaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_category",
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="basetransaction",
            name="type",
            field=models.CharField(
                choices=[("Expense", "Expense"), ("Income", "Income")],
                default="Expense",
                max_length=50,
            ),
        ),

    ]
