# Generated by Django 5.0.7 on 2024-12-26 17:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_income_basetransaction_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetransaction",
            name="id",
            field=models.CharField(
                default=api.models.generate_transaction_id,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
