# Generated by Django 5.0.7 on 2024-12-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_basetransaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basetransaction",
            old_name="id",
            new_name="transaction_id",
        ),
    ]
