# Generated by Django 5.0.7 on 2025-01-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_id_basetransaction_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="user_username",
            field=models.CharField(default="", editable=False, max_length=150),
        ),
    ]
