# Generated by Django 5.0.7 on 2025-01-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_budget_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetransaction",
            name="user_username",
            field=models.CharField(default="", editable=False, max_length=150),
        ),
    ]
