# Generated by Django 5.0.7 on 2025-01-01 08:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_basetransaction_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="basetransaction",
            name="transaction_id",
            field=models.CharField(
                default=api.models.generate_transaction_id, max_length=8
            ),
        ),
    ]
