# Generated by Django 5.0.7 on 2025-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_basetransaction_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
