# Generated by Django 5.0.7 on 2025-01-25 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_budget_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount_left",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="0.00", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="start_date",
            field=models.DateField(verbose_name=datetime.date(2025, 1, 25)),
        ),
    ]
