# Generated by Django 5.0.7 on 2024-12-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fyenanceuser",
            name="phone_no",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="fyenanceuser",
            name="session_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="fyenanceuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="fyenanceuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="fyenanceuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="fyenanceuser",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
