# Generated by Django 5.0.7 on 2024-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_fyenanceuser_phone_no_fyenanceuser_session_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fyenanceuser",
            name="session_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
