# Generated by Django 5.0.7 on 2024-12-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_fyenanceuser_session_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fyenanceuser",
            name="session_key",
        ),
    ]
