# Generated by Django 5.0.7 on 2024-12-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_fyenanceuser_account_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="fyenanceuser",
            name="account_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
