# Generated by Django 5.0.7 on 2024-12-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_fyenanceuser_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fyenanceuser",
            name="is_google_user",
            field=models.BooleanField(default=False),
        ),
    ]
