# Generated by Django 5.0.7 on 2024-12-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_fyenanceuser_is_google_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="fyenanceuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fyenanceuser",
            name="google_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
